### ISSUE TITLE
Arduino test suites not working on arduino-1.0-beta2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shovon134/arduino#621]
```
What steps will reproduce the problem?
1. Open ATS_Skeleton under Examples->ArduinoTestSuite
2. Click Verify


What is the expected output? What do you see instead?

Expected
========
No errors


Actual
======
In file included from C:\Program 
Files\arduino-0022\arduino-beta\arduino-1.0-beta2\libraries\ArduinoTestSuite/Ard
uinoTestSuite.h:11,
                 from ATS_Skeleton.cpp:11:
C:\Program 
Files\arduino-0022\arduino-beta\arduino-1.0-beta2\hardware\arduino\cores\arduino
/Arduino.h:203:26: error: pins_arduino.h: No such file or directory

What version of the Arduino software are you using? On what operating
system?  Which Arduino board are you using?

http://files.arduino.cc/downloads/arduino-1.0-beta2.zip

Win XP

Mega ADK

```

Original issue reported on code.google.com by `oldchurc...@gmail.com` on 2 Sep 2011 at 10:15
