### ISSUE TITLE
Matrix library broken in new-extension branch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shovon134/arduino#520]
```
Running the new-extension build on OSX 10.6, the following code:
#include <Matrix.h>                // swap out whatever library is 
appropriate below

void setup() {
}

void loop() {
}

-----------------------

Generates the following errors:


/Users/tigoe/Documents/arduino development 
stuff/gitRepo/Arduino/build/macosx/work/Arduino.app/Contents/Resources/Java/libr
aries/Matrix/Matrix.cpp:41:20: error: Sprite.h: No such file or directory
/Users/tigoe/Documents/arduino development 
stuff/gitRepo/Arduino/build/macosx/work/Arduino.app/Contents/Resources/Java/libr
aries/Matrix/Matrix.cpp: In member function 'void Matrix::write(uint8_t, 
uint8_t, Sprite)':

```

Original issue reported on code.google.com by `tom.i...@gmail.com` on 4 Apr 2011 at 11:36
