### ISSUE TITLE
Firmata broken in new-extension branch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shovon134/arduino#519]
```
Running the new-extension build on OSX 10.6, the following code:
#include <Firmata.h>                

void setup() {
}

void loop() {
}

-----------------------

Generates the following errors:

There's also an issue with Firmata under new-extension:


/Users/tigoe/Documents/arduino development 
stuff/gitRepo/Arduino/build/macosx/work/Arduino.app/Contents/Resources/Java/libr
aries/Firmata/Firmata.cpp: In function 'void sendValueAsTwo7bitBytes(int)':
/Users/tigoe/Documents/arduino development 
stuff/gitRepo/Arduino/build/macosx/work/Arduino.app/Contents/Resources/Java/libr
aries/Firmata/Firmata.cpp:32: error: 'BYTE' was not declared in this scope

And several identical errors....

```

Original issue reported on code.google.com by `tom.i...@gmail.com` on 4 Apr 2011 at 11:35
- Merged into: #447
