### ISSUE TITLE
SPI Library broken in new-extension branch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shovon134/arduino#518]
```
Running the new-extension build on OSX 10.6, the following code:
#include <SPI.h>                // swap out whatever library is 
appropriate below

void setup() {
}

void loop() {
}


Generates the following errors:

In file included from /Users/tigoe/Documents/arduino development 
stuff/gitRepo/Arduino/build/macosx/work/Arduino.app/Contents/Resources/Java/libr
aries/SPI/SPI.h:15,
                from /Users/tigoe/Documents/arduino development 
stuff/gitRepo/Arduino/build/macosx/work/Arduino.app/Contents/Resources/Java/libr
aries/SPI/SPI.cpp:12:
/Users/tigoe/Documents/arduino development 
stuff/gitRepo/Arduino/build/macosx/work/Arduino.app/Contents/Resources/Java/hard
ware/arduino/cores/arduino/pins_arduino.h:66: error: previous declaration of 
'const uint16_t port_to_mode_PGM []' with 'C++' linkage

And several other identical errors on other lines of pins_arduino.h

```

Original issue reported on code.google.com by `tom.i...@gmail.com` on 4 Apr 2011 at 11:34
